version: '3.4'

services:
  accounttransactionservice:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal;Initial Catalog=BankingSystem;Persist Security Info=False;User ID=sa;Password=123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=60;"
      InternalServices__CustomerService: "http://host.docker.internal:5001"
    ports:
      - "5002:80"
    networks:
      - apis-network

  customerprofileservice:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal;Initial Catalog=BankingSystem;Persist Security Info=False;User ID=sa;Password=123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=60;"
    ports:
      - "5001:80"
    networks:
      - apis-network

networks:
  apis-network:
    driver: bridge

