version: '3.4'

services:
  seq:
    image: datalust/seq:latest
    container_name: seq-instance
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    restart: unless-stopped
    networks:
      - apis-network

  accounttransactionservice:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5002
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal;Initial Catalog=BankingSystem;Persist Security Info=False;User ID=sa;Password=123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=60;"
      InternalServices__CustomerService: "http://host.docker.internal:5001"
      SeqUrl: "http://host.docker.internal:5341"
    ports:
      - "5002:5002"
    networks:
      - apis-network

  customerprofileservice:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5001
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal;Initial Catalog=BankingSystem;Persist Security Info=False;User ID=sa;Password=123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=60;"
      SeqUrl: "http://host.docker.internal:5341"
    ports:
      - "5001:5001"
    networks:
      - apis-network

networks:
  apis-network:
    driver: bridge

